set( pylon_VERSION_MAJOR 7)
set( pylon_VERSION_MINOR 2)
set( pylon_VERSION_SUBMINOR 0 )
if(APPLE)
    set( pylon_VERSION_SUFFIX ".${pylon_VERSION_MAJOR}.${pylon_VERSION_MINOR}.${pylon_VERSION_SUBMINOR}" )
elseif(WIN32)
    set( pylon_VERSION_SUFFIX "_v${pylon_VERSION_MAJOR}_${pylon_VERSION_MINOR}" )
elseif(UNIX)
    set( pylon_VERSION_SUFFIX ".${pylon_VERSION_MAJOR}.${pylon_VERSION_MINOR}.${pylon_VERSION_SUBMINOR}" )
else()
   set(_undefined_message "${_undefined_message} pylon_VERSION_SuFFIX not defined\n")
   message( SendError( "Unsupported Platform" ) )
endif()
